# Site settings
title: smartwatch-liste.de
email: info@smartwatch-liste.de
description: smartwatch-liste.de versucht einen Überblick über die verschiedenen Modelle auf dem Smartwatch-Markt zu liefern.

baseurl: "/smartwatch-liste" # the subpath of your site, e.g. /blog/
twitter_username: smartwatchliste
github_username: larswittenberg
timezone: Europe/Berlin


markdown: kramdown
# sass:
#  style: :compressed


defaults:
  - scope:
      path: ""
      type: smartwatch
    values:
      layout: smartwatch

collections:
  smartwatch:
    output: true
    permalink: /:path/
